InfoParse: InfoParse::Option_< bool > Class Template Reference
InfoParse::Option_< bool > Class Template Reference
Specialized Option_ for boolean values.
#include <Option_.hpp>
Public Member Functions
Option_ (std::string longName, char shortName, bool *exporter)
Constructs the Option_ with explicitly given SHORT name.
Option_ (const std::string &name, bool *exporter)
Constructs the Option_ with implicitly deducted SHORT name.
std::string match (const std::string &args) const
Tries to match either of the names of the Option_ to the supplied string.
bool operator== (const Option_ &rhs) const
Checks equality depending on equal LONG and SHORT names.
bool operator== (const std::string &name) const
Checks equality with checking whether the given string equals to LONG name.
bool operator== (const char *cname) const
Checks equality with checking whether the given c-string equals to LONG name.
bool operator== (char c) const
Checks equality with checking whether the given char equals to SHORT name.
bool operator!= (const Option_ &rhs) const
Checks inequality by negating the equality check.
bool operator!= (const std::string &name) const
Checks inequality with checking whether the given string does not equal to LONG name.
bool operator!= (const char *cname) const
Checks inequality with checking whether the given c-string does not equal to LONG name.
bool operator!= (char c) const
Checks inequality with checking whether the given char does not equal to SHORT name.
Detailed Description
template<>
class InfoParse::Option_< bool >
Specialized Option_ for boolean values.
Boolean values need not parse after either their option's name was present they simply dump true, otherwise false.
Stores one parsable option with a SHORT and LONG name.
LONG names are parsed like "--LONG", while SHORT names are parsed like "-SHORT", and SHORT names are one character long.
See also
Option_<T>
Constructor & Destructor Documentation
InfoParse::Option_< bool >::Option_ (std::string longName, char shortName, bool * exporter) inline
Constructs the Option_ with explicitly given SHORT name.
Parameters
longName The LONG name for the option.
shortName The SHORT name for the option
exporter The bool pointer to dump whether the switch was found
Note
exporter is not checked for nullptr
References Option_().
Referenced by Option_().
InfoParse::Option_< bool >::Option_ (const std::string & name, bool * exporter) inline
Constructs the Option_ with implicitly deducted SHORT name.
The SHORT name is generated as the first character of the LONG name.
Parameters
name The LONG name for the option. First character will used as the SHORT name
exporter The bool pointer to dump whether the switch was found
Note
exporter is not checked for nullptr
References Option_().
Referenced by Option_().
Member Function Documentation
std::string InfoParse::Option_< bool >::match (const std::string & args) const inline
Tries to match either of the names of the Option_ to the supplied string.
Parameters
args The string to match the LONG then if not found the SHORT name to
Returns
The string with the removed options' name For example: " text -s more text" -> " text more text "
bool InfoParse::Option_< bool >::operator!= (const Option_< bool > & rhs) const inline
Checks inequality by negating the equality check.
let A = lhs.LONG == rhs.LONG
let B = lhs.SHORT == rhs.SHORT
lhs != rhs iff !(A ∨ B)
References operator==().
bool InfoParse::Option_< bool >::operator== (const Option_< bool > & rhs) const inline
Checks equality depending on equal LONG and SHORT names.
let A = lhs.LONG == rhs.LONG
let B = lhs.SHORT == rhs.SHORT
lhs == rhs iff A ∨ B
Referenced by operator!=().
The documentation for this class was generated from the following file:
Option_.hpp