InfoParse: InfoParse::Option_< T > Class Template Reference
InfoParse::Option_< T > Class Template Reference
Stores one parsable option with a SHORT and LONG name.
#include <Option_.hpp>
Public Member Functions
Option_ (std::string longName, char shortName, T *exporter)
Constructs the Option_ with explicitly given SHORT name.
Option_ (const std::string &name, T *exporter)
Constructs the Option_ with implicitly deducted SHORT name.
std::string match (const std::string &args) const
Tries to match either of the names of the Option_ to the supplied string.
bool operator== (const Option_ &rhs) const
Checks equality depending on equal LONG and SHORT names.
bool operator== (const std::string &name) const
Checks equality with checking whether the given string equals to LONG name.
bool operator== (const char *cname) const
Checks equality with checking whether the given c-string equals to LONG name.
bool operator== (char c) const
Checks equality with checking whether the given char equals to SHORT name.
bool operator!= (const Option_ &rhs) const
Checks inequality by negating the equality check.
bool operator!= (const std::string &name) const
Checks inequality with checking whether the given string does not equal to LONG name.
bool operator!= (const char *cname) const
Checks inequality with checking whether the given c-string does not equal to LONG name.
bool operator!= (char c) const
Checks inequality with checking whether the given char does not equal to SHORT name.
Detailed Description
template<class T>
class InfoParse::Option_< T >
Stores one parsable option with a SHORT and LONG name.
LONG names are parsed like "--LONG", while SHORT names are parsed like "-SHORT", and SHORT names are one character long.
Template Parameters
T The type of the parameter to stuff the found value into.
See also
Option_<bool>
Constructor & Destructor Documentation
template<class T > InfoParse::Option_< T >::Option_ (std::string longName, char shortName, T * exporter) inline
Constructs the Option_ with explicitly given SHORT name.
Parameters
longName The LONG name for the option.
shortName The SHORT name for the option
exporter The pointer to a constructed memory whereto dump the found value
Note
exporter is not checked for nullptr
References InfoParse::Option_< T >::Option_().
Referenced by InfoParse::Option_< T >::Option_().
template<class T > InfoParse::Option_< T >::Option_ (const std::string & name, T * exporter) inline
Constructs the Option_ with implicitly deducted SHORT name.
The SHORT name is generated as the first character of the LONG name.
Parameters
name The LONG name for the option. First character will used as the SHORT name
exporter The pointer to a constructed memory whereto dump the found value
Note
exporter is not checked for nullptr
References InfoParse::Option_< T >::Option_().
Referenced by InfoParse::Option_< T >::Option_().
Member Function Documentation
template<class T > std::string InfoParse::Option_< T >::match (const std::string & args) const inline
Tries to match either of the names of the Option_ to the supplied string.
Parameters
args The string to match the LONG then if not found the SHORT name to
Returns
The string with the removed options' name and value For example: " text -b 4 more text" -> " text more text "
template<class T > bool InfoParse::Option_< T >::operator!= (const Option_< T > & rhs) const inline
Checks inequality by negating the equality check.
let A = lhs.LONG == rhs.LONG let B = lhs.SHORT == rhs.SHORT
lhs != rhs iff !(A ∨ B)
template<class T > bool InfoParse::Option_< T >::operator== (const Option_< T > & rhs) const inline
Checks equality depending on equal LONG and SHORT names.
let A = lhs.LONG == rhs.LONG let B = lhs.SHORT == rhs.SHORT
lhs == rhs iff A ∨ B
The documentation for this class was generated from the following file:
Option_.hpp